### ISSUE TITLE
Asking about abnormal predicted depth maps

### ISSUE THREAD

**Issue by HuynhLam** [zzangjinsun/NLSPN_ECCV20#12]
Hi,
This is such a great work, with impressing results!
I've tried to generate the depth maps using your pretrained model but somehow the depth image doesn't look good 
(Inputs from KITTI validation selection set).
![2011_09_26_drive_0002_sync_image_0000000005_image_02](https://user-images.githubusercontent.com/7226762/97849338-1505c200-1cfb-11eb-81d5-c039b8a133ea.png)
Predicted depth map
![0000000](https://user-images.githubusercontent.com/7226762/97849283-fc95a780-1cfa-11eb-84fa-2a595c90cdf2.png)
The only difference with yours recommended setting is that I don't have x4 GTX GPUs.
Can this be the reason that affect the final depth map? 
Thank you.

**Comment by zzangjinsun** [comment]
Hi @HuynhLam,

Did you use the latest code and the command I provided?

For the KITTI dataset with the pretrained model, the following arguments are important:

--max_depth 90.0 --num_sample 0 --preserve_input

Otherwise, could you let me know your input arguments?
(You can find args.json in the saving directory)

**Comment by HuynhLam** [comment]
Hi @zzangjinsun,
Thanks for your fast response.
I missed the _--preserve_input_ argument.
It works fine now. 
Thanks a lot! I am gonna close this issue.
