### ISSUE TITLE
question about code

### ISSUE THREAD

**Issue by Xuanmeng-Zhang** [zzangjinsun/NLSPN_ECCV20#14]
Hi, Park, I feel confused about the two-line code in nlspnmode.py as follows.
      
      
            offset_tmp[:, 0, :, :] = offset_tmp[:, 0, :, :] + hh - (self.k_f - 1) / 2
            offset_tmp[:, 1, :, :] = offset_tmp[:, 1, :, :] + ww - (self.k_f - 1) / 2

Can you explain the function of the two lines？What happens if I remove the two lines?

**Comment by zzangjinsun** [comment]
Hi @Xuanmeng-Zhang,

this process ensures offsets are initialized to a conventional 8-neighbor setup (i.e., 3x3 neighbors) because depending on the index, (hh - (self.k_f - 1) / 2, ww - (self.k_f - 1) / 2) falls into (-1, -1) to (1, 1).

I think you can remove these two lines and it makes the network learn all the neighbors' offset from zero without any initial values.

Hope this explanation is helpful for your understanding!

**Comment by Xuanmeng-Zhang** [comment]
Thank you for your answer. I get it！
