### ISSUE TITLE
module 'DCN' has no attribute 'modulated_deform_conv_forward'

### ISSUE THREAD

**Issue by forvd** [zzangjinsun/NLSPN_ECCV20#3]
module 'DCN' has no attribute 'modulated_deform_conv_forward'

**Comment by zzangjinsun** [comment]
Could you try with the following version of the DCN?

https://github.com/xvjiarui/Deformable-Convolution-V2-PyTorch

This version is the exact version I used.

Sorry for the inconvenience. I will modify the link in the readme accordingly.

**Comment by forvd** [comment]
I have tried the new one. It lost some ;  in the code.
After I add ; to code, still get the same error.
module 'DCN' has no attribute 'modulated_deform_conv_forward'

**Comment by zzangjinsun** [comment]
I updated the repo with the DCN module I used.

I found that some function names are different from those from [here](https://github.com/xvjiarui/Deformable-Convolution-V2-PyTorch). (Because they updated module names later.)

It should work now.

If you want to use the latest version, I think you can use **modulated_deform_conv2d_forward** instead of **modulated_deform_conv_forward**.

Please check it, and thank you for letting me know about this issue!

**Comment by forvd** [comment]
It works now. Thank you

**Comment by jikerWRN** [comment]
Hi, when i compile DCN downloaded from https://github.com/xvjiarui/Deformable-Convolution-V2-PyTorch, i meet error 
" 2 errors detected in the compilation of "/tmp/tmpxft_00008c8e_00000000-6_modulated_deform_conv2d_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1".
may i know your pytorch version and environment config? Thanks!

**Comment by zzangjinsun** [comment]
Please try with the codes I uploaded, but it seems that there is another problem with your environment!

For my environment, please refer to [here](https://github.com/zzangjinsun/NLSPN_ECCV20#dependencies).
