### ISSUE TITLE
Confidence map decoder and inference runtime 

### ISSUE THREAD

**Issue by eduardo-r** [zzangjinsun/NLSPN_ECCV20#4]
Hello, I was wondering if you could share  what's the intuition behind the Confidence Branch of the decoder? I might have missed it in the paper but all I could find is that you use the confidence of a pixel to weigh/refine the final depth.
In Eq (9)
<img src="https://render.githubusercontent.com/render/math?math=c_{i,j} = \in \[ 0,1 \]">

Also, I was wondering the requirements for inference or if you mind sharing some numbers regarding framerate or computation times of you implementation. I can see some info for training e.g. 4x1080Ti and one day of training for NYU data, I was just wondering what about inference? Thanks

**Comment by zzangjinsun** [comment]
The intuition behind the confidence-incorporation is that affinity alone cannot appropriately handle outliers because relevant pixels in the RGB image is sometimes contaminated by noisy input depth values.
In other words, affinity describes the relevance of neighbor pixels and confidence represents the reliability of them.
Please refer to the Sec.4.2 of the paper.

The average inference time on the KITTI DC dataset is 0.22 sec, which is reported in [here](http://www.cvlibs.net/datasets/kitti/eval_depth_detail.php?benchmark=depth_completion&result=654d83dbc9b128494c3704897c156f057f6346ff).

**Comment by eduardo-r** [comment]
Thanks for your quick reply. I really appreciate it!
My first question was more in terms of the implementation. I see the confidence decoder is a ReLu+Conv2d+Sigmoid, I wonder where did you take inspiration for that? Seems to work quite well and better that alternatives. Thanks

**Comment by zzangjinsun** [comment]
I designed the confidence branch based on the init depth/guidance branches.
As you can see in the [init depth branch](https://github.com/zzangjinsun/NLSPN_ECCV20/blob/6f67ee893190a7722516eb83ebda9105ec1ed7ad/src/model/nlspnmodel.py#L256) and the [confidence branch](https://github.com/zzangjinsun/NLSPN_ECCV20/blob/6f67ee893190a7722516eb83ebda9105ec1ed7ad/src/model/nlspnmodel.py#L272), the confidence branch is the parameter reduced version of the init depth branch.

For depth/guidance branches, they should predict a wide range of depth values or many neighbors (=8 neighbors). However, confidence is a single constant for each pixel, therefore, I expected that fewer number of parameters would be okay (and it works reasonably). Of course, sigmoid is used to map confidence values to the range [0, 1].

Thx!!

**Comment by eduardo-r** [comment]
I see, thanks a lot!
